server:
  port: 8899

logging:
  file:
    name: userManager.log
    path: logs

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT
    username: root
    password: zj123456
  mvc:
    servlet:
      load-on-startup: 1

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*